systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl

# Gradle configuration
org.gradle.jvmargs=-Xmx8192m -Xms8192m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel.threads=12
org.gradle.parallel=true
org.gradle.daemon=false

# loom
loom.ignoreDependencyLoomVersionValidation=true

# DGT
dgt.minecraft.revision=3

# Mod properties
mod.name=PackCore
mod.id=packcore
mod.version=3.0.2
mod.group=com.github.kd_gaming1

# Dependencies
midnightlib_version_1_21_5=1.7.3+1.21.4-fabric
midnightlib_version_1_21_8=1.7.5+1.21.6-fabric

modmenu_version_1_21_5=14.0.0-rc.2
modmenu_version_1_21_8=15.0.0

owo_version_1_21_5=0.12.21+1.21.5
owo_version_1_21_8=0.12.23+1.21.8

lavender_md_version_1_21_5=0.1.2+1.21.5
lavender_md_version_1_21_8=0.1.2+1.21.8

sodium_version_1_21_5=mc1.21.5-0.6.13-fabric
sodium_version_1_21_8=mc1.21.8-0.7.2-fabric

iris_version_1_21_5=1.8.11+1.21.5-fabric
iris_version_1_21_8=1.9.6+1.21.8-fabric
