# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=4.1.6
mod.group=com.github.kd_gaming1
mod.id=packcore
mod.name=Pack Core

# Global dependencies
deps.fabric_loader=0.18.4
deps.scamscreener_version=2.1.2

# Versioned dependencies
deps.fabric_api=[VERSIONED]
deps.uilib_version=[VERSIONED]
deps.midnightlib_version=[VERSIONED]
deps.hm_api_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.scaleme_version=[VERSIONED]

deps.sodium_version=[VERSIONED]
deps.iris_version=[VERSIONED]

publish.modrinth=V3FnL7QV
publish.curseforge=1375477
